blog/urls.py
from django.contrib import admin
from django.urls import path
from . import settings
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('django.contrib.auth.urls')),
    path("", include("main.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls)),
    ]

main/urls.py
from django.urls import path
from . import views

app_name = "blog-main"

urlpatterns = [
    path('', views.PostList.as_view(), name="artile-list"),
    path('<int:pk>', views.PostDetails.as_view(), name='article-detail'),
    path('save_twit', views.save_twit, name='twit-save'),
    path('registrate_user', views.UserReg.as_view(), name="user-reg"),
    path('blogger', views.BloggerList.as_view(), name='blogger-list'),
    path('blogger/<int:pk>', views.BloggerArticlesList.as_view(), name='blogger-article-list'),
    path('create', views.CreateNewArticle.as_view(), name='new-article'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Blogger(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    blogger = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"


class Article(models.Model):
    author = models.ForeignKey(Blogger, on_delete=models.CASCADE, blank=False, verbose_name="Автор")
    title = models.CharField(max_length=120, help_text="Основна ідея поста", verbose_name="Заголовок")
    text = models.TextField(max_length=1000, verbose_name="Текст")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="Дата публікації")

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return "Article:" + self.title + " " + str(self.pub_date)


class Twit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Загловок")
    autor = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="")
    text = models.CharField(max_length=150, help_text="Комент")
    pud_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Twtit on Article " + self.article.title + " by the user " + self.autor.username + " " + str(self.pud_date)

    @property
    def date(self):
        return self.pud_date

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from main.models import Twit, Article


class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    blogger = forms.BooleanField(initial=False, help_text="Хочете бути блогером?", required=False, label='Блогер')

    class Meta:
        model = User
        fields = ['username', 'email']

    # Validation password
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise ValidationError("Password don't mach")

        return cd['password']


class FormTwitModel(forms.ModelForm):
    class Meta:
        model = Twit
        # exclude = ()
        fields = ['text', ]


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text', ]

main/views.py
from django.contrib import messages
from django.contrib.admin.templatetags.admin_list import pagination
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.views import generic

from .forms import RegisterUserForm, FormTwitModel, ArticleCreateForm
from .models import Article, Twit, Blogger


class PostList(generic.ListView):
    model = Article
    paginate_by = 5
    # queryset = Article.objects.filter(text__contains=self.request.GET.get('q') )

    def get_queryset(self):
        result = super(PostList, self).get_queryset()
        if self.request.GET.get('q'):
            result = result.filter(text__contains=self.request.GET.get('q'))
        return result


class PostDetails(generic.DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super(PostDetails, self).get_context_data(**kwargs)
        context['form_twit'] = FormTwitModel
        return context


@login_required
def save_twit(request):
    if request.POST:
        print(request.POST)
        twit = Twit()
        twit.article_id = int(request.POST['pk'][0])
        twit.autor_id = int(request.POST['username'][0])
        twit.text = request.POST['text'].strip()
        if len(twit.text.strip())<2:
            messages.success(request, "Sorry. Your comment is wrong.")
            return redirect(to=request.POST['url'])
        if Twit.objects.filter(text=request.POST['text']):
            messages.success(request, "Sorry. There is such comment")
        else:
            twit.save()
        twit.url = request.POST['url']
        return redirect(to=twit.url)
    else:
        redirect(to='/')


class UserReg(generic.CreateView):
    form_class = RegisterUserForm
    template_name = 'main/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseForbidden()

        return super(UserReg, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        Blogger.objects.create(user=user, blogger=form.cleaned_data['blogger'])
        login(request=self.request, user=user)
        return redirect(to='/')


class BloggerList(generic.ListView):
    model = Blogger
    queryset = Blogger.objects.exclude(user__is_active=False).exclude(blogger=False)


class BloggerArticlesList(generic.DetailView):
    model = Blogger
    paginate_by = 5


class CreateNewArticle(generic.CreateView, LoginRequiredMixin):
    model = Article
    form_class = ArticleCreateForm

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author_id = int(self.request.POST['author'])
        if len(Article.objects.filter(title=article.title)) and len(article.text.strip())>10:
            messages.success(self.request, "Sorry there is such Article")
        else:
            article.save()
        return redirect(to='/')

main/templates/generic_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static '../statics/css/my.css' %}"/>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <style></style>
</head>
<body>
{#_____________nav-bar______________________________________________#}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">All posts</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog-main:blogger-list' %}">Blogger list <span class="sr-only">(current)</span></a>
            </li>

            {% if user.blogger %}
                <li class="nav-item">
                            <span class="navbar-text" style="margin-left: 5px">
                        <a href="{% url 'blog-main:new-article' %}">Create new Post</a>

                </li>
            {% endif %}

            <li class="nav-item active">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'logout' %}">Logout - {{ user.username }}<span class="sr-only">(current)</span></a>
                {% else %}
                    <a class="nav-link" href="{% url 'blog-main:user-reg' %}">Sign in<span class="sr-only">(current)</span></a>
                {% endif %}
            </li>


            {#      <li class="nav-item dropdown">#}
            {#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
            {#          Dropdown#}
            {#        </a>#}
            {#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
            {#          <a class="dropdown-item" href="#">Action</a>#}
            {#          <a class="dropdown-item" href="#">Another action</a>#}
            {#          <div class="dropdown-divider"></div>#}
            {#          <a class="dropdown-item" href="#">Something else here</a>#}
            {#        </div>#}
            {#      </li>#}
            {#      <li class="nav-item">#}
            {#        <a class="nav-link disabled" href="#">Disabled</a>#}
            {#      </li>#}
        </ul>

        {% if not user.is_authenticated %}
            <form class="form-inline " method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <div class="form-group mb-2">
                    <label class="sr-only"> Login</label>
                    <input type="text" class="form-control" name="username">

                </div>
                <div class="form-group mx-sm-3 mb-2">
                    <label class="sr-only"> Password</label>
                    <input type="password" class="form-control" name="password">

                    {#                        {{ form_register.as_p }}#}
                    <input type="submit" class="btn btn-primary" style="margin-left: 10px" value="Login">
            </form>
        {% else %}
            <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'blog-main:artile-list' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        {% endif %}
    </div>
</nav>
{#___________nav-bar_____________________________________________________#}
{% if messages %}
    <ul class="message">
        {% for message in messages %}
            <li> {{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


<div style='margin-left: 15px'>
    {% block content %}{% endblock %}
</div>

{% if is_paginated %}
    <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
    </div>
{% endif %}

</body>
</html>

main/templates/main/article_detail.html
{% extends "main/../generic_template.html" %}
{% block title %}Articles{% endblock %}


{% block content %}

    <p><strong>{{ article.title| escapejs }}</strong>
        <small>{{ article.pub_date }}</small>
        {{ article.author }} </p>

    <p class="main-text"> {{ article.text }}</p>

    {% if article.twit_set.all %}
        {% for coment in article.twit_set.all %}
            <p><strong>{{ coment.autor }}</strong>
                - <small>{{ coment.date|date:""}}</small></p>
            <p>{{ coment.text }}</p>
            <hr>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
        <form method="post" , action="{% url 'blog-main:twit-save' %}">
            {% csrf_token %}
            <input type="hidden" name="username" value="{{ user.id }}">
            <input type="hidden" name="pk" value="{{ article.id }}">
            <input type="hidden" name="url" value="{% url 'blog-main:article-detail' article.id %}">
            {{ form_twit.as_table }}
            <input type="submit" value="Відгук">
        </form>
    {% endif %}
    <hr>

{% endblock %}

main/templates/main/article_form.html
{% extends 'generic_template.html' %}

{% block title %}
    Створення нового цікавого повідомлення
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'blog-main:new-article' %}">
        {% csrf_token %}
        <input type="hidden" name="author" value="{{ user.blogger.id }}">
        {{ form.as_p }}
        <input type="submit" value="Створити">
    </form>
{% endblock %}

main/templates/main/article_list.html
{% extends "generic_template.html" %}
{% block title %}Articles{% endblock %}

{% block content %}


    {% if article_list %}
        {% for article in article_list %}
            <p><strong> <a href="{% url 'blog-main:article-detail' article.id %} ">
                {{ article.title| escapejs }}</strong>
                </a>
                <small>{{ article.pub_date }}</small>
                {{ article.author }} </p>
            <hr>
        {% endfor %}

    {% else %}
        <p>На жаль поки що нема постів</p>
    {% endif %}
{% endblock %}

main/templates/main/blogger_detail.html
{% extends "generic_template.html" %}
{% block title %}Articles{% endblock %}

{% block content %}

    {% if object%}
        <h3>{{ blogger.user.username|capfirst }}
            <small> Articles:
            {% if not blogger.article_set.all.count %}
                0
            {% else %}
                {{ blogger.article_set.all.count }}
            {% endif %}
            </small>
        </h3>

        {% if not blogger.article_set.all %}
            <p>Постів поки що нема </p>
        {% else %}
            <h4>Posts: </h4>
        {% endif %}

        {% for article in blogger.article_set.all %}
            <h5><a href="{% url 'blog-main:article-detail' article.id %} ">{{ article.title }} </a>
                - <small class="gray">{{ article.pub_date }}</small></h5>
            <p>{{  article.text}} </p>
            <hr>
        {% endfor %}
    {% else %}
        <p>На жаль поки що нема постів</p>
    {% endif %}
{% endblock %}

main/templates/main/blogger_list.html
{% extends "generic_template.html" %}
{% block title %}Articles{% endblock %}

{% block content %}

    {% if object_list %}
        {% for blogger in blogger_list %}
            <h5><a href="{% url 'blog-main:blogger-article-list' blogger.id%}">{{ blogger.user.username }}</a></h5>
            <h6> Articles: {{ blogger.article_set.all.count }}</h6>
            <hr>
{#            {% for article in bloger.user.article_set.all %}#}
{#                <p><strong> <a href="{% url 'blog-main:article-detail' article.id %} ">#}
{#                    {{ article.title| escapejs }}</strong>#}
{#                    </a>#}
{#                    <small>{{ article.pub_date }}</small>#}
{#                <p class="main-text"> {{ article.text[25] }}</p>#}
{#                <hr>#}
{##}
{#            {% endfor %}#}
        {% endfor %}
    {% else %}
        <p>На жаль поки що нема постів</p>
    {% endif %}
{% endblock %}

main/templates/main/user_registration.html
{% extends 'generic_template.html' %}

{% block title %}User registration{% endblock %}

{{% block content %}
    <form method="post" action="{% url 'blog-main:user-reg' %}" style="width: 50%">
        {% csrf_token %}

{#        {% for field in form_reg %}#}
{#            <div class="form-group" style="alignment: center">#}
{#            <label>{{ field.label_tag }}</label>#}
{#                {% if field.help_text %}#}
{#                    <small style="color: gray">{{ field.help_text }}</small>#}
{#                {% endif %}#}
{##}
{##}
{##}
{#            <input class="form-control" aria-describedby="emailHelp"#}
{#                    {% if field.name  == 'email' %}#}
{#                        type="email"#}
{#                        placeholder="Enter email"#}
{#                    {% elif 'password' in field.name %}#}
{#                        type="password"#}
{#                        placeholder="Enter password"#}
{#                    {% else %}#}
{#                        type="text"#}
{#                    {% endif%}#}
{##}
{#                   name="{{ field.name }}">#}
{#            <small id="emailHelp" class="form-text text-muted"></small>#}
{#        </div>#}
{#        {% endfor %}#}


        {{ form.as_p }}
{##}
{#        <div class="form-group">#}
{#            <label for="exampleInputEmail1">name</label>#}
{#            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"#}
{#                   name="username">#}
{#            <small id="emailHelp" class="form-text text-muted"></small>#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <label for="exampleInputEmail1">Email address</label>#}
{#            <input type="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email"#}
{#                   name="email">#}
{#            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <label for="exampleInputPassword1">Password</label>#}
{#            <input type="password" class="form-control" placeholder="Password" name="password">#}
{#        </div>#}
        {#  <button type="submit" class="btn btn-primary">Submit</button>#}


        {#    {{ form_reg.as_table }}#}
        {#    </div>#}
        <input type="submit" value="Відправити">
    </form>

{% endblock %}